#!/bin/bash

author=`git config --get user.name`

commits() {
  git log --author="$author" --no-merges --format="%ad %s" --date=short --date-order
}

main() {
  LAST_DATE=""
  BODY=""

  commits | sort -gs -t ' ' -k1 |
    {
      while read COMMIT; do
        DATE=`echo $COMMIT | cut -d ' ' -f1`
        SUBJECT=`echo $COMMIT | cut -d ' ' -f2-`

        if [ "$LAST_DATE" != "$DATE" ]; then
          echo $BODY

          LAST_DATE=$DATE
          BODY=""

          echo
          echo
          echo [$DATE]
        fi

        BODY="$SUBJECT. $BODY"
      done

      echo $BODY
    }
}

main | less
