# Config here!

tab_bar_edge top
tab_bar_style separator
tab_separator " ┇ "

map ctrl+shift+page_up next_tab
map ctrl+shift+page_down previous_tab
map ctrl+shift+enter new_tab_with_cwd

font_size 12.0

scrollback_lines 20000
