include ${HOME}/dotfiles/.config/kitty/kitty-common.conf

# Tab navigation
map ctrl+shift+page_up next_tab
map ctrl+shift+page_down previous_tab
map ctrl+shift+enter new_tab_with_cwd

# Font
font_size 12.0
